version: '3'

services:
  flickrawr-code-server:
    image: flickrawr-code-server:latest
    restart: always
    volumes:
      - ./:/home/coder/project
    ports:
      - '8443:8443'
      - '8080:8080'
    command: --allow-http --no-auth